name: Show Me the S3cr3tz
on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{ secrets.NEXUS_KEY }}
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{secrets.NEXUS_KEY}} | sed 's/./& /g'