name: Update Releases
concurrency: update-releases
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - source
    paths:
      - "mods.json"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2
        with:
          version: 6.23.6
          run_install: true
      - name: Build
        run: |
          cd fetch-mods
          pnpm run build
      - name: Get local Mod Database file
        id: local-mods
        run: echo "::set-output name=mods::$(< ./mods.json sed ':a;N;$!ba;s/\n/ /g')"
      - name: Fetch mod releases and manifests
        id: fetch-mods
        uses: ./fetch-mods
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN  }}
          discord-mod-hook-urls: ${{ secrets.DISCORD_MOD_HOOK_URLS }}
          mods: "${{ steps.local-mods.outputs.mods }}"
          discord-hook-url: "${{ secrets.DISCORD_HOOK_URL }}"
          nexus-api-key: "${{ secrets.NEXUS_KEY }}"
      - uses: actions/checkout@v2
        with:
          ref: "main"
          fetch-depth: 0
      - name: Write database to file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: database.json
          contents: "${{ steps.fetch-mods.outputs.releases }}"
          write-mode: overwrite
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          branch: "main"
          commit_message: Update mod database
          commit_user_name: Smol Ame Mod Database
          commit_user_email: database@smolamemods.netlify.app
          commit_author: Smol Ame Mod Database <database@smolamemods.netlify.app>
